org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true
fabric.loom.dropNonIntermediateRootMethods=true

mod.id=bigger_fish
mod.name=There's Always a Bigger Fish
mod.group=cc.cassian.bigger_fish
mod.version=1.2.4

deps.fabric-loader=0.19.2

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.kaleido=0.3.3+1.3.2
deps.fabric_asm=v2.3

publish.modrinth=tKKzcK6F
publish.curseforge=
#publish.additionalVersions=