modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "bigger_fish"
displayName = "There's Always a Bigger Fish"
version = "${version}"
displayURL = "https://modrinth.com/mod/always-a-bigger-fish"
logoFile = "assets/bigger_fish/icon.png"
authors = "cassiancc, malice-and-meat, Kobber"
description = '''A rework of fishing mechanics, adding new biome-specific fish to catch, a new fishing rod that can have bait attached, and more'''
rrv_client = "cc.cassian.bigger_fish.compat.rrv.RrvIntegration"

[[mixins]]
config = "bigger_fish.mixins.json"

[[dependencies.bigger_fish]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bigger_fish]]
modId = "minecraft"
type = "required"
versionRange = "[26, 27]"
