deps.minecraft=1.21.5
deps.neoforge=21.5.95
deps.parchment=1.21.5:2025.06.15

deps.eiv = 2.4.2+1.21.5
deps.jei =  21.3.2.22
deps.rei = 19.0.806
deps.cloth_config = 18.0.145
deps.modmenu = 14.0.0-rc.2
deps.compost = daUmk48q
deps.item_descriptions = 2.5.1+1.21.5
deps.fdrf = 1.21.5-3.2.4
deps.iteminteractions=21.5.0