deps.minecraft=1.21.10
deps.fabric-api=0.138.4+1.21.10
deps.parchment=1.21.10:2025.10.12
deps.mojbackward=3

publish.additionalVersions=1.21.9

deps.eiv = 5.0.2+1.21.10
deps.jei = 26.2.0.28
deps.rei = 20.0.811
deps.cloth_config = 19.0.147
deps.modmenu = 16.0.0-rc.1
deps.compost = toPdBJmj
deps.item_descriptions = 2.6.0+1.21.10
deps.fd = 1.21.10-3.4.1
deps.iteminteractions=21.10.0