modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/cassiancc/Always-A-Bigger-Fish/issues"
license = "MIT"

[[mods]]
modId = "bigger_fish"
version = "${version}"
displayName = "Always a Bigger Fish"
authors = "cassiancc"
description = '''
A rework of fishing mechanics, adding new biome-specific fish to catch, a new fishing rod that can have bait attached, and a fishing minigame!
'''
#logoFile = ""

[[dependencies.bigger_fish]]
modId = "neoforge"
type = "required"
versionRange = "[21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bigger_fish]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bigger_fish]]
modId = "architectury"
type = "required"
versionRange = "[16.1.4,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "bigger_fish.mixins.json"
