modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/cassiancc/Always-A-Bigger-Fish/issues"
license = "Multiple"

[[mods]]
modId = "bigger_fish"
version = "${version}"
displayName = "There's Always a Bigger Fish"
authors = "cassiancc, malice-and-meat"
description = '''
A rework of fishing mechanics, adding new biome-specific fish to catch, a new fishing rod that can have bait attached, and a fishing minigame!
'''
logoFile = "assets/bigger_fish/icon.png"

[[dependencies.bigger_fish]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.181,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bigger_fish]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "bigger_fish.mixins.json"

eiv = "cc.cassian.bigger_fish.compat.eiv.EivIntegration"