deps.minecraft=26.1-snapshot-1
deps.fabric-api=0.140.0+26.1

deps.eiv = 5.0.2+1.21.10
deps.jei = 27.0.0.1
deps.rei = 20.0.811
deps.cloth_config = 21.11.151
deps.modmenu = 17.0.0-alpha.1
deps.compost = gds3rWvh
deps.item_descriptions = 2.6.0+26.1-snapshot-1
deps.fd = 1.21.11-3.4.2
deps.iteminteractions=21.11.0